### PR TITLE
Smoke tests for Web Service Faker 

### PR DESCRIPTION
**Pull request by melezhik**
HI @polettix !

This is a [simple sparrow based test suite](https://github.com/melezhik/web-service-fake-smoke) for WebService::Fake. Just runnign wsf and hitting a couple of routes and checking an output.  An example travis report is here - https://travis-ci.org/melezhik/WebService-Fake/jobs/181606399

If you if like it , please merge in.

PS let me know if you have any questions.
PS2 if it sounds *not interesting* just close PR, I will be ok :)  

---
Regards, Alexey

### CODE REVIEW

**Comment by polettix** [comment]
Hi Alexey!

I have no objection in helping you with your project (I'll hopefully come to understand it at last!).

One thing I'm not entirely convinced about is the inclusion of the pre-requisites and build and install phase as explicit steps in the `before_install` phase. I mean, it's a little weird that you `install` in `before_install`, isn't it?

Can you try to reshape according to [travis-perl-helpers](https://github.com/travis-perl/helpers) ?

PS: instead of adding more commits, I would suggest to start from the current HEAD of *my* fork and then do a `push -f`.

PPS: I'd also suggest you to use different branches from `master` in *your* fork, or you might have problems when I merge the PR (e.g. if I decide to squash things).

**Comment by melezhik** [comment]
Hi @polettix nice to hear from you. )) Ok I will reshape a travis.yaml and update my PR ...

**Comment by melezhik** [comment]
The head version of your travis.yml looks like

```
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
- perl -V
```

BTW I can't see any tests invocation here (./Build test), however your travis reports shows you had one , I am not against any structure of .travis.yml, from my side I probably need these steps:

* install Sparrow and web-service-fake-smoke plugin (pre/install part?)
* run smoke tests against your module by `sparrow plg run web-service-fake-smoke`

So, let's figure out on structure of .travis.yml

**Comment by melezhik** [comment]
@polettix , sorry never mind my last comment , I have examined https://github.com/travis-perl/helpers , probably I understand what you mean , I will come up with new update soon ...

**Comment by polettix** [comment]
I might have made it clearer that I was referring to [Example Long .travis.yml](https://github.com/travis-perl/helpers#example-long-travisyml) as you eventually figured out...

**Pull request closed without merging**
